# Generated by Django 5.0.7 on 2025-07-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('order', models.FloatField(default=0, verbose_name='優先順位')),
                ('text', models.CharField(max_length=1000, verbose_name='テキスト')),
            ],
        ),
    ]
