# Generated by Django 5.0.7 on 2025-09-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='introduction',
            field=models.TextField(verbose_name='紹介文（HTML可）'),
        ),
    ]
