# Generated by Django 5.0.7 on 2025-09-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_circle_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='紹介文（HTML可）'),
        ),
    ]
